theme: jekyll-theme-minimal
title: Elizabeth Popov
description: >
  My personal research website  
  <br><br>
  <img src="/elizabethp.github.io/assets/TF_DNA.png" alt="DNA" style="max-width:120px; margin-top:10px;">
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom CSS
include:
  - assets/style.css
